name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Run install
        run: npm install

      - name: Build site
        run: npm start

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    if: github.ref == 'refs/heads/github_actions'
    
    steps:
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
